server:
  servlet:
    context-path: /
spring:
  application:
    name: demo-camunda
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_camunda
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  main:
    web-application-type: servlet
  jpa:
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo