spring:
  application:
    name: demo-camunda
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_camunda
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  main:
    web-application-type: servlet
